/********************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 ********************************************************************/
package org.eclipse.fennec.search.osgi;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.fennec.emf.osgi.eobject.registry.EObjectProvider;
import org.eclipse.fennec.emf.osgi.eobject.registry.EObjectRegistryWriter;
import org.eclipse.fennec.emf.osgi.metadata.MetadataService;
import org.eclipse.fennec.search.esearch.IndexUnitMapping;
import org.eclipse.fennec.search.mapping.AspectMappingSource;
import org.eclipse.fennec.search.mapping.MappingGenerator;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.component.annotations.Reference;
import org.osgi.service.component.annotations.ReferenceCardinality;
import org.osgi.service.component.annotations.ReferencePolicy;
import org.osgi.service.component.annotations.ReferencePolicyOption;

/**
 * Publishes <em>generated</em> mappings into the search mapping registry, for EPackages a
 * deployment names (#51) — the registry road of {@link MappingGenerator}, using the
 * extension point §4.1 already provides rather than inventing a fourth delivery path.
 * <p>
 * <b>Configuration is required</b> ({@code ConfigurationPolicy.REQUIRE}) and the packages
 * are named one by one: generating for whatever happens to be registered would turn a
 * proposal into ambient runtime behaviour, and a generated mapping guesses from attribute
 * names where conventions deliberately do not. Naming the package is the deployment
 * saying "I know, and I want it here".
 *
 * <pre>
 * generateFor = ["https://example.org/catalog"]
 * </pre>
 * <p>
 * Two things it refuses to do. It <b>never generates for a package that ships its own
 * mapping</b> as an {@code esearch} metadata aspect — the model already answered, and
 * generating beside that answer would put two mappings in one registry. And it writes
 * under the ordinary registry key (the mapping's name), so an authored file in a
 * higher-precedence provider still wins; the generated one is visible where an operator
 * looks, not hidden behind a lookup.
 * <p>
 * Every generated mapping is logged with the generator's reasoning, at INFO — an index
 * whose shape nobody authored must at least be able to say where that shape came from.
 *
 * @author Data In Motion Consulting
 */
@Component(name = "SearchGeneratedMappings", configurationPolicy = ConfigurationPolicy.REQUIRE,
		property = "emf.eobject.provider.name=" + GeneratedMappingProvider.PROVIDER_NAME,
		service = EObjectProvider.class)
public class GeneratedMappingProvider implements EObjectProvider {

	/** The provider name a registry configuration targets to pick these mappings up. */
	public static final String PROVIDER_NAME = "search-generated-mappings";

	private static final Logger LOG = System.getLogger(GeneratedMappingProvider.class.getName());

	/** Which EPackages get a generated mapping, by nsURI. */
	public @interface GeneratorConfig {

		/** nsURIs of the packages to generate for; nothing is generated by default. */
		String[] generateFor() default {};
	}

	private final Map<String, EPackage> packages = new ConcurrentHashMap<>();
	private final Set<String> generateFor;
	private volatile MetadataService metadata;
	private volatile EObjectRegistryWriter writer;

	@Activate
	public GeneratedMappingProvider(GeneratorConfig config) {
		this.generateFor = Set.of(config.generateFor());
	}

	@Reference(cardinality = ReferenceCardinality.MULTIPLE, policy = ReferencePolicy.DYNAMIC,
			policyOption = ReferencePolicyOption.GREEDY)
	void addPackage(EPackage ePackage) {
		if (generateFor.contains(ePackage.getNsURI())) {
			packages.put(ePackage.getNsURI(), ePackage);
			// A package that registers after the initial load still gets its mapping: the
			// registry is live, and an EPackage service arriving late is the ordinary case.
			publish(ePackage);
		}
	}

	void removePackage(EPackage ePackage) {
		packages.remove(ePackage.getNsURI(), ePackage);
	}

	@Reference(cardinality = ReferenceCardinality.OPTIONAL, policy = ReferencePolicy.DYNAMIC,
			policyOption = ReferencePolicyOption.GREEDY)
	void setMetadata(MetadataService metadata) {
		this.metadata = metadata;
	}

	void unsetMetadata(MetadataService metadata) {
		this.metadata = null;
	}

	@Override
	public CompletableFuture<Void> load(EObjectRegistryWriter writer) {
		this.writer = writer;
		packages.values().forEach(this::publish);
		// The registry may publish with nothing generated yet — a configured package whose
		// EPackage service is not up is a timing question, not a failed load.
		return CompletableFuture.completedFuture(null);
	}

	private void publish(EPackage ePackage) {
		EObjectRegistryWriter target = writer;
		if (target == null) {
			return;
		}
		if (shipsItsOwnMapping(ePackage)) {
			LOG.log(Level.INFO, "Package ''{0}'' ships an ''{1}'' aspect of its own; generating beside "
					+ "it would put two mappings in one registry, so nothing is generated.",
					ePackage.getNsURI(), AspectMappingSource.ASPECT_TYPE_ID);
			return;
		}
		MappingGenerator.Suggestions suggestions = MappingGenerator.forPackage(ePackage).generate();
		IndexUnitMapping mapping = suggestions.mapping();
		target.put(PROVIDER_NAME, mapping.getName(), mapping, Map.of());
		LOG.log(Level.INFO, "Generated the mapping of unit ''{0}'' from ''{1}'' — nobody authored one. "
				+ "Author it before the index carries data you would miss. The generator''s reasoning:",
				mapping.getName(), ePackage.getNsURI());
		suggestions.explanations().forEach(explanation -> LOG.log(Level.INFO, "  {0}", explanation));
	}

	/**
	 * Whether the model carries its own mapping on the metadata plane (§4.1). Asked of the
	 * aspect itself rather than through a lookup by unit name — a shipped mapping names its
	 * unit whatever the model author chose, and "did the model already answer" must not
	 * depend on that name matching ours.
	 */
	private boolean shipsItsOwnMapping(EPackage ePackage) {
		MetadataService service = metadata;
		if (service == null) {
			return false;
		}
		return service.getPackageAspect(ePackage, AspectMappingSource.ASPECT_TYPE_ID)
				.filter(aspect -> aspect.getContent() instanceof IndexUnitMapping)
				.isPresent();
	}
}
